services:
  sprezz-web:
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - nw-jaeger
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  sprezz-jaeger:
    container_name: sprezz-jaeger
    image: jaegertracing/jaeger
    networks:
      - nw-jaeger
    ports:
      - "4317:4317"
      - "8084:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  nw-jaeger:
    driver: bridge
